version: '3.8'
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak-oracle:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    environment:
      - "KC_HOSTNAME=localhost"
      - "KC_PROXY=edge"
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=password"
      - "KC_HTTP_PORT=8081"
      - "KC_DB=oracle"
      - "KC_DB_URL=jdbc:oracle:thin:@//oracle-oracledb21c-1:1521/ORCLPDB"
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=keycloak"
    command: [ "start-dev" ]
    ports:
      - "8081:8081"
    networks:
      - microservices-demo
      - development
    healthcheck:
      test: [ "CMD-SHELL", "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/$${KC_HTTP_PORT:-8081}' || exit 1" ]
      interval: 10s
      timeout: 2s
      retries: 5
networks:
  microservices-demo:
    name: ${GLOBAL_NETWORK:-development}
    external: true
  development:
    external: true